header:
  logoTitle: PENZION
contact:
  title: Kontaktujte nás
  cz: Česká Republika
map:
  button: Zvětšit mapu
gallery:
  title: Penzion a okolí
links:
  title: Zajimavé odkazy
  links:
    link1: Pronájem Sokolov
    link2: Stránky města Oloví
    link3: Stránky města Sokolov
    link4: Stránky města Karlovy Vary
